# Generated by Django 3.2 on 2021-04-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apeido', models.CharField(max_length=30)),
                ('apodo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, upload_to='images/user', verbose_name='perfil')),
            ],
        ),
    ]
