# Generated by Django 3.2 on 2021-04-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('m2_construccion', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('m2_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('num_habitaciones', models.IntegerField(blank=True, default=0, verbose_name='Numero de cuartos')),
                ('num_banos', models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, verbose_name='Numero de baños')),
                ('estacionamiento', models.IntegerField(blank=True, default=0, verbose_name='Numero de estacionamientos')),
                ('amenidades', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, max_length=500)),
                ('calle', models.CharField(blank=True, max_length=40)),
                ('numero_ext', models.CharField(blank=True, max_length=8)),
                ('numero_int', models.CharField(blank=True, max_length=4)),
                ('colonia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(default='Tijuana', max_length=40)),
                ('estado', models.CharField(default='Baja California', max_length=40)),
                ('pais', models.CharField(default='Mexico', max_length=40)),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='longitud')),
                ('featured', models.BooleanField(default=True, verbose_name='Aparece en el landing>?')),
                ('tipo_contrato', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta')], default='Venta', max_length=15)),
                ('termino', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('m2_construccion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nivel', models.IntegerField(default=0, verbose_name='Nivel')),
                ('num_habitaciones', models.IntegerField(default=0, verbose_name='Numero de cuartos')),
                ('num_banos', models.IntegerField(default=0, verbose_name='Numero de baños')),
                ('estacionamiento', models.IntegerField(default=0, verbose_name='Numero de estacionamientos')),
                ('notas', models.TextField(blank=True, max_length=500)),
                ('calle', models.CharField(max_length=40)),
                ('numero_ext', models.CharField(max_length=8)),
                ('numero_int', models.CharField(max_length=4)),
                ('colonia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(default='Tijuana', max_length=40)),
                ('estado', models.CharField(default='Baja California', max_length=40)),
                ('pais', models.CharField(default='Mexico', max_length=40)),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='longitud')),
                ('featured', models.BooleanField(default=True, verbose_name='Aparece en el landing>?')),
                ('tipo_contrato', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta')], default='Venta', max_length=15)),
                ('termino', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('m2_construccion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('num_habitaciones', models.IntegerField(default=0, verbose_name='Numero de cuartos')),
                ('num_banos', models.IntegerField(default=0, verbose_name='Numero de baños')),
                ('estacionamiento', models.IntegerField(default=0, verbose_name='Numero de estacionamientos')),
                ('amenidades', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, max_length=500)),
                ('calle', models.CharField(max_length=40)),
                ('numero_ext', models.CharField(max_length=8)),
                ('numero_int', models.CharField(max_length=4)),
                ('colonia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(default='Tijuana', max_length=40)),
                ('estado', models.CharField(default='Baja California', max_length=40)),
                ('pais', models.CharField(default='Mexico', max_length=40)),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='longitud')),
                ('featured', models.BooleanField(default=True, verbose_name='Aparece en el landing>?')),
                ('tipo_contrato', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta')], default='Venta', max_length=15)),
                ('termino', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('m2_terreno', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notas', models.TextField(blank=True, max_length=500)),
                ('calle', models.CharField(max_length=40)),
                ('numero_ext', models.CharField(max_length=8)),
                ('numero_int', models.CharField(max_length=4)),
                ('colonia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(default='Tijuana', max_length=40)),
                ('estado', models.CharField(default='Baja California', max_length=40)),
                ('pais', models.CharField(default='Mexico', max_length=40)),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='longitud')),
                ('featured', models.BooleanField(default=True, verbose_name='Aparece en el landing>?')),
                ('tipo_contrato', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta')], default='Venta', max_length=15)),
                ('termino', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
        ),
        migrations.CreateModel(
            name='TerrenoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/casa', verbose_name='Imagen')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacional.terreno')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentosImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/casa', verbose_name='Imagen')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacional.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='ComercioImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/casa', verbose_name='Imagen')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacional.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='CasaImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/casa', verbose_name='Imagen')),
                ('alt', models.CharField(blank=True, max_length=40)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacional.casa')),
            ],
        ),
    ]
