# Generated by Django 3.2 on 2021-04-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0002_casa_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/landing', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='comercioimagen',
            name='alt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/landing', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='departamentosimagen',
            name='alt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='terreno',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/landing', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='terrenoimagen',
            name='alt',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
