# Generated by Django 3.2 on 2021-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0003_auto_20210412_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='calle',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='numero_ext',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='numero_int',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='calle',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nivel',
            field=models.IntegerField(blank=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='numero_ext',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='numero_int',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='calle',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='numero_ext',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='numero_int',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
