# Generated by Django 3.2 on 2021-04-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_citas'),
        ('habitacional', '0005_casa_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.user'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.user'),
        ),
        migrations.AddField(
            model_name='terreno',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.user'),
        ),
        migrations.AlterField(
            model_name='comercioimagen',
            name='imagen',
            field=models.ImageField(upload_to='images/comercios', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='departamentosimagen',
            name='imagen',
            field=models.ImageField(upload_to='images/departamentos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='terrenoimagen',
            name='imagen',
            field=models.ImageField(upload_to='images/terrenos', verbose_name='Imagen'),
        ),
    ]
