# Generated by Django 3.2 on 2021-04-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0006_auto_20210420_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='terreno',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='casa',
            name='featured',
            field=models.BooleanField(default=True, verbose_name='Quieres que aparesca en la pagina principal?'),
        ),
    ]
