# Generated by Django 3.2.1 on 2021-05-09 00:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0007_auto_20210425_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='notas',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
