# Generated by Django 3.2.1 on 2021-05-09 00:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0008_alter_casa_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='notas',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='notas',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='notas',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
